export const aboutData = {
  beginning: 'I started programming by accident. I was working as a customer service agent at a software company. I took an online CS class to sound more knowledgeable when talking to customers. I thought the course would teach me about servers. The topic of the class was programming with C instead. I\'ve completed a ten-month web development boot camp, gone back to college for computer science, deployed two full-stack projects, and created a portfolio in the two years since then.',
  webPreferences: 'I like to use the MERN stack to build applications. I\'m comfortable working on the front end or the back end. I also love tinkering with new technologies. I\'m learning how to use the Ant Design library, which I used to create this page. It\'s awesome!',
  farmApp: 'I also like programming with C++. I recently built a farm application, which allowed users to create a farm and calculate financial figures. The app used many object-oriented principles like polymorphism, inheritance, and composition. It could also add animals and crops to the farm dynamically using pointers and vectors.',
  goals: 'I became a web developer to turn exciting ideas into a reality. My goal is to solve problems, help people, protect the environment, and contribute to the world.',
  places: 'I grew up in Minnesota. I earned a Bachelor of Science in Business Administration from the University of South Carolina. After college, I moved to California, where I worked in the film industry as a camera assistant. I\'ve lived in Austin, Texas, since 2021.',
  college: 'I started studying computer science at Glendale Community College in August 2020. I plan to continue my education at Oregon State University.',
  movies: 'I like movies, books, shows, video games, and anything with a great story. My favorite movie is Aliens. The last book I read was Dune. I\'m currently watching Ted Lasso.',
  bike: 'I also like riding my bike. I bought a Trek hybrid when I moved to Texas, so I\'ve been spending my time riding in the country. The best part about it is seeing the horses and cows. The worst part is getting chased by dogs.'
};